### PR TITLE
Don't set a value attribute on label tags

### PR DESCRIPTION
**Pull request by sshaw**
A value attribute on a label tag is invalid.

Not the biggest fan of the fix but since the function is already modifying the caller's hash ~~it's the least invasive option...~~ **UPDATE** just used `#update` instead of adding `:value => nil` to the caller's hash.

### CODE REVIEW

**Comment by ujifgc** [comment]
Why is there `:value` in the first place? If anything we should fix `#label` to not use `#default_options`, I think.

**Comment by sshaw** [comment]
> Why is there :value in the first place?

`default_options` sets `field_value` on each call.

>  If anything we should fix #label to not use #default_options, I think.

Yeah I agree. I'll update shortly.

**Comment by sshaw** [comment]
Actually I think doing what `field_field` does makes more sense: call `Hash#except(:value)` on `default_options`'s return value. 

I've updated my commit to do that.

`default_options

**Comment by ujifgc** [comment]
We can't use ActiveSupport's `Hash#except`.

**Comment by sshaw** [comment]
Okay, I've removed the calls to `Hash#except`.

**Pull request merged**
