### PR TITLE
use hamlit

### PR DESCRIPTION
**Pull request by ujifgc**
This PR adopts Hamlit as default Haml engine.

Ref: #2115

### CODE REVIEW

**Comment by namusyaka** [comment]
Hamlit seems like to have some incompatibilities yet. https://github.com/k0kubun/hamlit/blob/master/REFERENCE.md#limitations

**Comment by ujifgc** [comment]
Should we keep Haml as default and use Hamlit engine only if it's in the project Gemfile?

**Comment by namusyaka** [comment]
I'd like to hear more opinions on this. @padrino/core-members

**Comment by sshaw** [comment]
If you're looking towards a 1.0 release, how many minor releases would it take before you deem the Padrino/hamlit combination stable? Though I guess the same can be said about erubi too. Isn't it the default for ERB now?

**Comment by adam12** [comment]
> Though I guess the same can be said about erubi too. Isn't it the default for ERB now?

It's now the default for the latest releases of Tilt and Rails. It's also the default for Padrino apps requiring an ERb renderer.

**Comment by ujifgc** [comment]
Erubi implementation is almost exact copy of a part of Erubis. Hamlit and Haml are very different implementations.

**Comment by wikimatze** [comment]
Can't we just use both? I think older apps will break (see the fact @namusyaka mentioned), if we just use hamlit in the next release.

**Comment by basex** [comment]
This PR introduced a bug on my system. I'm not using HAML in any place and I get:
```bash
$ bundle exec padrino console
.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- haml (LoadError)
	from .rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from .rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from .rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from .rvm/gems/ruby-2.4.0/gems/tilt-2.0.7/lib/tilt/haml.rb:2:in `<top (required)>'
	from .rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from .rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from .rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from .rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from .rvm/gems/ruby-2.4.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:243:in `block in lazy_load'
	from .rvm/gems/ruby-2.4.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:241:in `each'
	from .rvm/gems/ruby-2.4.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:241:in `lazy_load'
	from .rvm/gems/ruby-2.4.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:216:in `lookup'
	from .rvm/gems/ruby-2.4.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:154:in `[]'
	from .rvm/gems/ruby-2.4.0/gems/tilt-2.0.7/lib/tilt.rb:53:in `template_for'
	from .rvm/gems/ruby-2.4.0/gems/padrino-helpers-0.14.1/lib/padrino-helpers/output_helpers/haml_handler.rb:5:in `<module:OutputHelpers>'
	from .rvm/gems/ruby-2.4.0/gems/padrino-helpers-0.14.1/lib/padrino-helpers/output_helpers/haml_handler.rb:3:in `<module:Helpers>'
	from .rvm/gems/ruby-2.4.0/gems/padrino-helpers-0.14.1/lib/padrino-helpers/output_helpers/haml_handler.rb:2:in `<module:Padrino>'
	from .rvm/gems/ruby-2.4.0/gems/padrino-helpers-0.14.1/lib/padrino-helpers/output_helpers/haml_handler.rb:1:in `<top (required)>'
	from .rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from .rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from .rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from .rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from .rvm/gems/ruby-2.4.0/gems/padrino-support-0.14.1/lib/padrino-support/file_set.rb:23:in `block in glob_require'
	from .rvm/gems/ruby-2.4.0/gems/padrino-support-0.14.1/lib/padrino-support/file_set.rb:14:in `block in glob'
	from .rvm/gems/ruby-2.4.0/gems/padrino-support-0.14.1/lib/padrino-support/file_set.rb:14:in `each'
	from .rvm/gems/ruby-2.4.0/gems/padrino-support-0.14.1/lib/padrino-support/file_set.rb:14:in `glob'
	from .rvm/gems/ruby-2.4.0/gems/padrino-support-0.14.1/lib/padrino-support/file_set.rb:23:in `glob_require'
	from .rvm/gems/ruby-2.4.0/gems/padrino-helpers-0.14.1/lib/padrino-helpers.rb:9:in `<top (required)>'
	from .rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from .rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from .rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from .rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from .rvm/gems/ruby-2.4.0/gems/padrino-0.14.1/lib/padrino.rb:4:in `<top (required)>'
	from .rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require'
	from .rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
	from .rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
	from .rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
	from .rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
	from .rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
	from .rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
	from config/boot.rb:12:in `<top (required)>'
```

**Pull request merged**
