### PR TITLE
Add circle ci badge and further ruby/jruby versions for running tests

### PR DESCRIPTION
**Pull request by wikimatze**
In order to activate the badge a repo owner must setup the project
Screenshot_2022-01-23_06-36-07

I can PM you the invite link.

Cheers!

### CODE REVIEW

**Comment by nesquena** [comment]
Thanks! Let me know what you need me to do and I'll set it up

**Comment by wikimatze** [comment]
Drop you a mail.

**Comment by wikimatze** [comment]
@nesquena build tab is still not activate? Do you have the rights to setup the circle-ci account for Padrino? Otherwise we only see the build status in MRs.

**Comment by nesquena** [comment]
> @nesquena build tab is still not activate? Do you have the rights to setup the circle-ci account for Padrino? Otherwise we only see the build status in MRs.

@wikimatze I didn't get your email, will check spam. Will also do my best to set it up anyhow.

**Comment by nesquena** [comment]
@wikimatze I believe project is now created and should be working for `padrino-framework` repo, can you confirm? Let me know if you need anything else on my end

**Comment by wikimatze** [comment]
@nesquena It's working now, thank you very much.

**Pull request merged**
