### PR TITLE
Remove rack dependency and temporary show_exceptions code

### PR DESCRIPTION
**Pull request by namusyaka**
Sinatra 1.4.6 has been released :tada:

### CODE REVIEW

**Comment by ujifgc** [comment]
Should we in this case also restrict Sinatra version to '~> 1.4.6' or at least give a warning?

**Comment by namusyaka** [comment]
Right.

**Comment by dariocravero** [comment]
:dancers:

**Comment by nesquena** [comment]
Nice! Will release the next beta for 0.13.0 soon!

**Pull request merged**
