### PR TITLE
Bump to newer version of Ruby

### PR DESCRIPTION
**Pull request by rogerhu**

### CODE REVIEW

**Comment by nesquena** [comment]
@rogerhu Thanks for submitting this, makes sense to remove the old rubyforge property and unlock bundler to support 2.0 as well. Unclear if we would actually have to change our usage of bundler at all in order to support 2.0 in gen, hopefully not.  

However, right now the tests are failing, it looks relatively minor in terms of failures, but this wouldn't make sense to merge until we can get the test cases passing again.

**Comment by aldentea** [comment]
> However, right now the tests are failing, it looks relatively minor in terms of failures, but this wouldn't make sense to merge until we can get the test cases passing again.

As I pointed out at #2221, the failure seems to be caused by the update of Sinatra, and I have one [solution](https://travis-ci.org/aldentea/padrino-framework/builds/642725419) to the issue. 

(The reason I don't make PR is that I think it's better to update the test case than to match the test case with a monkey patch.)

**Comment by rogerhu** [comment]
Thanks for the lead into the issue.  I think this is expected behavior.  If I put a breakpoint in the code with the changes mentioned in https://github.com/sinatra/sinatra/pull/1566/files in the `padrino-core/lib/padrino-core/application/routing.rb` file, I can see that the body is setting the URL that's missing as the body.

```
[1122, 1131] in /Users/rogerh/.rvm/gems/ruby-2.6.3/gems/sinatra-2.0.8.1/lib/sinatra/base.rb
   1122:         status(500)
   1123:       end
   1124: 
   1125:       status(500) unless status.between? 400, 599
   1126: 
=> 1127:       boom_message = boom.message if boom.message && boom.message != boom.class.name
   1128:       if server_error?
   1129:         dump_errors! boom if settings.dump_errors?
   1130:         raise boom if settings.show_exceptions? and settings.show_exceptions != :after_handler
   1131:       elsif not_found?
(byebug) boom.message
"GET /"
```

Later in this function the message gets set:
```
   1131:       elsif not_found?
=> 1132:         headers['X-Cascade'] = 'pass' if settings.x_cascade?
   1133:         body boom_message || '<h1>Not Found</h1>'
```

Later we see this thing gets set as the response:

```
#<Sinatra::Response:0x00007fc82073de68 @status=404, @headers={"Content-Type"=>nil, "X-Cascade"=>"pass"}, @writer=#<Method: Sinatra::Response(Rack::Response::Helpers)#append>, @block=nil, @body=["GET /"], @buffered=true, @length=0>

[918, 927] in /Users/rogerh/.rvm/gems/ruby-2.6.3/gems/sinatra-2.0.8.1/lib/sinatra/base.rb
   918:       @response['Content-Type'] = nil
   919:       invoke { dispatch! }
   920:       invoke { error_block!(response.status) } unless @env['sinatra.error']
   921: 
   922:       unless @response['Content-Type']
=> 923:         if Array === body and body[0].respond_to? :content_type
   924:           content_type body[0].content_type
   925:         else
   926:           content_type :html
   927:         end
(byebug) body[0]
"GET /"
```

**Comment by rogerhu** [comment]
Ruby 2.6.3. seems to pass.  There are other issues on Ruby 2.7.0.

**Comment by nesquena** [comment]
Thanks!

**Pull request merged**
