### PR TITLE
FIXED: url(...) tries to match routes not compatible with missing par…

### LINKED ISSUE #2219: Problem with url(...) with multiple matched routes
#### Do you want to request a *feature* or report a *bug*?

bug

#### What is the current behavior?

Assume we have the following controller:
``` ruby
bash-5.0# cat app/controllers/test.rb
Test::App.controllers :test do

  get :foo, with: [:one, :two] do
    "world"
  end

  get :foo, with: :one do
    "hello"
  end

end
```

`Test::App.url(:test, :foo, one: "one")` shall match the second route `with: :one`, not the first `with: [:one, :two]`. However, the first one is actually taken and thus raises an error like below:

``` ruby
bash-5.0# bundle exec padrino c
=> Loading development console (Padrino v.0.14.4)
=> Loading Application Test::App
irb(main):001:0> Test::App.url(:test, :foo, one: "one")
Traceback (most recent call last):
       16: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
       15: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
       14: from /usr/local/bundle/gems/padrino-core-0.14.4/lib/padrino-core/cli/base.rb:43:in `console'
       13: from (irb):1
       12: from /usr/local/bundle/gems/padrino-core-0.14.4/lib/padrino-core/application/routing.rb:343:in `url'
       11: from /usr/local/bundle/gems/padrino-core-0.14.4/lib/padrino-core/application/routing.rb:432:in `make_path_with_params'
       10: from /usr/local/bundle/gems/padrino-core-0.14.4/lib/padrino-core/path_router.rb:70:in `path'
        9: from /usr/local/bundle/gems/padrino-core-0.14.4/lib/padrino-core/path_router/matcher.rb:44:in `expand'
        8: from /usr/local/bundle/gems/mustermann-1.1.0/lib/mustermann/ast/pattern.rb:108:in `expand'
        7: from /usr/local/bundle/gems/mustermann-1.1.0/lib/mustermann/expander.rb:152:in `expand'
        6: from /usr/local/bundle/gems/mustermann-1.1.0/lib/mustermann/expander.rb:182:in `with_rest'
        5: from /usr/local/bundle/gems/mustermann-1.1.0/lib/mustermann/expander.rb:150:in `expand'
        4: from /usr/local/bundle/gems/mustermann-1.1.0/lib/mustermann/ast/expander.rb:97:in `expand'
        3: from /usr/local/bundle/gems/mustermann-1.1.0/lib/mustermann/ast/expander.rb:97:in `fetch'
        2: from /usr/local/bundle/gems/mustermann-1.1.0/lib/mustermann/ast/expander.rb:97:in `block in expand'
        1: from /usr/local/bundle/gems/mustermann-1.1.0/lib/mustermann/ast/expander.rb:120:in `error_for'
Mustermann::ExpandError (cannot expand with keys [:one], possible expansions: [:one, :two])
```

The following patch seems to solve the problem, although I'm not sure it is a perfect solution.
``` diff
bash-5.0# diff -u padrino-core-0.14.4/lib/padrino-core/path_router.rb.org padrino-core-0.14.4/lib/padrino-core/path_router.rb
--- padrino-core-0.14.4/lib/padrino-core/path_router.rb.org
+++ padrino-core-0.14.4/lib/padrino-core/path_router.rb
@@ -56,7 +56,7 @@
       #
       def path(name, *args)
         params = args.last.is_a?(Hash) ? args.pop : {}
-        candidates = @routes.select { |route| route.name == name }
+        candidates = @routes.select { |route| route.name == name && (route.matcher.names - params.keys.map(&:to_s)).length == 0 }
         fail InvalidRouteException if candidates.empty?
         route = candidates.sort_by! { |candidate|
           (params.keys.map(&:to_s) - candidate.matcher.names).length }.shift
```

#### What is the expected behavior?

```
irb(main):001:0> Test::App.url(:test, :foo, one: "one")
=> "/test/foo/one"
```

#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?

Ruby on Docker image `ruby:2.6-alpine` with Padrino 0.14.4

### PR DESCRIPTION
**Pull request by takeshi-yashiro**
This PR fixes #2219. 

Expected to solve the issue discussed here as well:
https://gitter.im/padrino/padrino-framework?at=5eba64c920eaac185304305b

### CODE REVIEW

**Comment by nesquena** [comment]
Thanks!

**Comment by nesquena** [comment]
@takeshi-yashiro Do you feel test coverage is already sufficient or do you think it makes sense to add a test to verify this is working correctly?

**Comment by takeshi-yashiro** [comment]
> @takeshi-yashiro Do you feel test coverage is already sufficient or do you think it makes sense to add a test to verify this is working correctly?

I assume adding the following test is a good idea. (Test content is the same as the existing test, 'should recognize route even if paths are duplicated' in test_routing.rb, but in reversed route definition order)
```
  it 'should recognize route even if paths are duplicated, in reverse order' do
    mock_app do
      get(:index, :with => :id, :provides => :json) {}
      get(:index, :with => :id) {}
      get(:index) {}
    end
    assert_equal "/", @app.url_for(:index)
    assert_equal "/1234", @app.url_for(:index, :id => "1234")
    assert_equal "/1234.json?baz=baz", @app.url_for(:index, :id => "1234", :format => "json", :baz => "baz")
  end
```

I confirmed that master branch before this PR fails the above test fails with the following error, while the current master does not.
```
  1) Error:
Routing#test_0006_should recognize route even if paths are duplicated, in reverse order:
Mustermann::ExpandError: cannot expand with keys [], possible expansions: [:format, :id] or [:id]
    /opt/homebrew/lib/ruby/gems/3.0.0/gems/mustermann-1.1.1/lib/mustermann/ast/expander.rb:121:in `error_for'
    /opt/homebrew/lib/ruby/gems/3.0.0/gems/mustermann-1.1.1/lib/mustermann/ast/expander.rb:98:in `block in expand'
    /opt/homebrew/lib/ruby/gems/3.0.0/gems/mustermann-1.1.1/lib/mustermann/ast/expander.rb:98:in `fetch'
    /opt/homebrew/lib/ruby/gems/3.0.0/gems/mustermann-1.1.1/lib/mustermann/ast/expander.rb:98:in `expand'
    /opt/homebrew/lib/ruby/gems/3.0.0/gems/mustermann-1.1.1/lib/mustermann/expander.rb:150:in `expand'
    /opt/homebrew/lib/ruby/gems/3.0.0/gems/mustermann-1.1.1/lib/mustermann/expander.rb:182:in `with_rest'
    /opt/homebrew/lib/ruby/gems/3.0.0/gems/mustermann-1.1.1/lib/mustermann/expander.rb:152:in `expand'
    /opt/homebrew/lib/ruby/gems/3.0.0/gems/mustermann-1.1.1/lib/mustermann/ast/pattern.rb:108:in `expand'
    /Users/takeshi/iniad-edu-system/padrino-framework/padrino-core/lib/padrino-core/path_router/matcher.rb:44:in `expand'
    /Users/takeshi/iniad-edu-system/padrino-framework/padrino-core/lib/padrino-core/path_router.rb:70:in `path'
    /Users/takeshi/iniad-edu-system/padrino-framework/padrino-core/lib/padrino-core/application/routing.rb:432:in `make_path_with_params'
    /Users/takeshi/iniad-edu-system/padrino-framework/padrino-core/lib/padrino-core/application/routing.rb:343:in `url'
    /Users/takeshi/iniad-edu-system/padrino-framework/padrino-core/test/test_routing.rb:105:in `block (2 levels) in <top (required)>'
```

I have added this test as https://github.com/takeshi-yashiro/padrino-framework/commit/e9953ad67802f40c63ea5d77d46a663d9ba79277. Shall I submit a PR for this test as well?

**Comment by nesquena** [comment]
A PR for that test would be great thank you!

**Pull request merged**
