### PR TITLE
Add test-unit component

### PR DESCRIPTION
**Pull request by namusyaka**

### CODE REVIEW

**Comment by namusyaka** [comment]
I'm going to finish off this pull request during the next week ;)

**Comment by namusyaka** [comment]
@padrino/core-members Could you review this pr?

**Comment by nesquena** [comment]
FWIW looks good to me, adapted from the code for minitest component right. My question is (may be stupid) why would someone pick test/unit over minittest nowadays?

**Comment by namusyaka** [comment]
I'm thinking, [test-unit](https://github.com/test-unit/test-unit) is very promising because it has actively been developed for quite a while and it's having a lot of features not found in minitest.
Also currently, the gem is very popular in Japan.

**Pull request merged**
