### PR TITLE
Wrap sequel rake tasks into a wrapper file

### PR DESCRIPTION
**Pull request by wikimatze**
This is my first bigger piece of minitest in Ruby. Feel free to review my test class as well as the wrapper.

### CODE REVIEW

**Comment by wikimatze** [comment]
Strange, the tests are running on my machine ...

**Comment by wikimatze** [comment]
Ahh, even a previously green build like https://travis-ci.org/padrino/padrino-framework/builds/255797254 is red. It fails with the error:

```bash
You have skipped tests. Run with --verbose for details.

cd /home/travis/build/padrino/padrino-framework/padrino-gen && /home/travis/.rvm/rubies/ruby-2.1.5/bin/ruby -S rake test

/home/travis/.rvm/rubies/ruby-2.1.5/bin/ruby -I"lib:test:../padrino/test" -I"/home/travis/.rvm/gems/ruby-2.1.5/gems/rake-12.0.0/lib" "/home/travis/.rvm/gems/ruby-2.1.5/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/test_app_generator.rb" "test/test_cli.rb" "test/test_component_generator.rb" "test/test_controller_generator.rb" "test/test_generator.rb" "test/test_helper_generator.rb" "test/test_mailer_generator.rb" "test/test_migration_generator.rb" "test/test_model_generator.rb" "test/test_plugin_generator.rb" "test/test_project_generator.rb" "test/test_sql_helpers.rb" "test/test_task_generator.rb" "test/test_sequel_rake_wrapper.rb" 

Run options: --seed 34607

# Running:

........E..........S.............................................................................................................................................................................................................................................S..........

Fabulous run in 9.362195s, 28.6258 runs/s, 165.7731 assertions/s.

  1) Error:

PluginGenerator::with resolving urls#test_0002_should resolve gist url properly:

Errno::ENOENT: No such file or directory @ rb_sysopen - https://gist.github.com/357045

    /home/travis/build/padrino/padrino-framework/padrino-gen/lib/padrino-gen/generators/runner.rb:128:in `initialize'

    /home/travis/build/padrino/padrino-framework/padrino-gen/lib/padrino-gen/generators/runner.rb:128:in `open'

    /home/travis/build/padrino/padrino-framework/padrino-gen/lib/padrino-gen/generators/runner.rb:128:in `execute_runner'

    /home/travis/build/padrino/padrino-framework/padrino-gen/lib/padrino-gen/generators/project.rb:56:in `setup_project'

    /home/travis/.rvm/gems/ruby-2.1.5/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'

    /home/travis/.rvm/gems/ruby-2.1.5/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'

    /home/travis/.rvm/gems/ruby-2.1.5/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `block in invoke_all'

    /home/travis/.rvm/gems/ruby-2.1.5/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `each'

    /home/travis/.rvm/gems/ruby-2.1.5/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `map'

    /home/travis/.rvm/gems/ruby-2.1.5/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `invoke_all'

    /home/travis/build/padrino/padrino-framework/padrino-gen/test/test_plugin_generator.rb:69:in `block (4 levels) in <top (required)>'

268 runs, 1552 assertions, 0 failures, 1 errors, 2 skips

You have skipped tests. Run with --verbose for details.

rake aborted!

Command failed with status (1): [ruby -I"lib:test:../padrino/test" -I"/home/travis/.rvm/gems/ruby-2.1.5/gems/rake-12.0.0/lib" "/home/travis/.rvm/gems/ruby-2.1.5/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/test_app_generator.rb" "test/test_cli.rb" "test/test_component_generator.rb" "test/test_controller_generator.rb" "test/test_generator.rb" "test/test_helper_generator.rb" "test/test_mailer_generator.rb" "test/test_migration_generator.rb" "test/test_model_generator.rb" "test/test_plugin_generator.rb" "test/test_project_generator.rb" "test/test_sql_helpers.rb" "test/test_task_generator.rb" "test/test_sequel_rake_wrapper.rb" ]

/home/travis/.rvm/gems/ruby-2.1.5/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'

Tasks: TOP => test
```

I'll try to fix the location of the gist.

**Comment by ujifgc** [comment]
Please, rebase against master. Do not include merge commits in your PR.

**Comment by wikimatze** [comment]
@ujifgc I'm done with rebasing => merge commit is removed.

**Comment by wikimatze** [comment]
By the way, is it okay that I've marked the `'should resolve gist url properly'` test as skipped?

**Comment by ujifgc** [comment]
Nope. It has nothing to do with this PR, no?

**Comment by wikimatze** [comment]
@ujifgc no, it had/has been an error when the travis build run. Should I remove the commits for this change for this PR so that it can be finally merged?

**Comment by wikimatze** [comment]
Ping @ujifgc again for a merge.

**Comment by ujifgc** [comment]
It is not okay to skip the test that has nothing to do with the PR.

**Comment by wikimatze** [comment]
I understand. I'll create a new Pull Request only with the necessary files.

**Pull request closed without merging**
