### PR TITLE
Improve memory usage and performance, closes #1975

### LINKED ISSUE #1975: Memory usage in 0.13.0
My project has 70 controllers, contains 1297 routes. The source file size is 4 MB.
When use 0.13, the startup process is slow, about 1 minute. 
After startup, the memory is larger than 880 MB. 

Use 0.12.5, starup process is just 10 seconds, and the memory is just 122 MB after startup.

Environment:
Ruby v2.2
Puma v2.14
CentOS 6.5

### PR DESCRIPTION
**Pull request by namusyaka**
In response to #1975, I've re-implemented new approach for recognizing route.
The 0.13.0's approach has big regexps, so our router requires too memory.
New approach doesn't require big regexps and memory. But, I think it will be faster than 0.12.5.

@ujifgc @nesquena  @cookiebody @padrino/core-members Could you confirm this?

### CODE REVIEW

**Comment by ujifgc** [comment]
>1k routes

0.13 (startup time: pain)
```
Running Padrino::HugeRouterBenchmark
total kB          231760   35056   28024
bench_calling_sample     0.005048        0.017663        0.078489        0.540538        5.297700
total kB          991860  712340  705156
```

0.13 + performance-improvement (startup time: real    0m3.305s)
```
Running Padrino::HugeRouterBenchmark
total kB          231796   34980   28040
bench_calling_sample     0.005799        0.017696        0.078529        0.493369        5.438216
total kB          264384   63488   56460
```

0.13 + performance-improvement + uri_decode: false (startup time: real    0m3.079s)
```
Running Padrino::HugeRouterBenchmark
total kB          231996   35244   28284
bench_calling_sample     0.005627        0.017697        0.076640        0.485587        4.819504
total kB          262484   61652   54540
```

0.12.5 (startup time: real    0m1.834s)
```
Running Padrino::HugeRouterBenchmark
total kB          236804   40020   32952
bench_calling_sample     0.004978        0.016153        0.063133        0.272677        1.118724
total kB          293592   92832   85612
```

Well, looks like we beat memory usage.

**Comment by namusyaka** [comment]
Disabled `:uri_decode`

**Comment by namusyaka** [comment]
Can I merge this? Any changes can be contained?

**Comment by ujifgc** [comment]
Yeah, it's good.

**Comment by namusyaka** [comment]
@ujifgc Thank you for your benchmark and useful memory profiling code.

**Pull request merged**
