### PR TITLE
Switch to ruby 2.1

### PR DESCRIPTION
**Pull request by namusyaka**

### CODE REVIEW

**Comment by ujifgc** [comment]
We do not want to replace rockets in our entire codebase. This is absolutely pointless.

One could argue for replacing rockets in the docs and the generated apps code.

**Comment by namusyaka** [comment]
>We do not want to replace rockets in our entire codebase. This is absolutely pointless.

Why? Should we continue to use hash rockets in our code base?

**Comment by sshaw** [comment]
https://github.com/padrino/padrino-framework/issues/1804#issuecomment-61222868

**Comment by ujifgc** [comment]
Closing in favor of #2169

**Pull request closed without merging**
