### PR TITLE
Display Error Message When Generator Template Cannot Be Loaded. 

### PR DESCRIPTION
**Pull request by sshaw**
RE: #2152 ~(not real fix though 😿)~.

Not sure that the code fixed in 49f296a is even used.

### CODE REVIEW

**Comment by sshaw** [comment]
I've updated this with a fix for the underlying Thor issue. 

There are a couple ways to fix this, let me know if you'd prefer a different approach.

**Comment by ujifgc** [comment]
Merged manually with a fix eeab412916af8ae02123c678e0f54feb6a3f7ae1

**Comment by sshaw** [comment]
What about the fix for Thor, which is the true fix for #2152?

**Comment by ujifgc** [comment]
What about it? We use 'open-uri' in https://github.com/padrino/padrino-framework/blob/12c29887aa3649545f7b01b21f68ac3103072985/padrino-gen/lib/padrino-gen/generators/runner.rb#L129 and I fixed it.

**Comment by sshaw** [comment]
Great!

**Pull request closed without merging**
