### PR TITLE
Circleci project setup

### PR DESCRIPTION
**Pull request by wikimatze**

### CODE REVIEW

**Comment by wikimatze** [comment]
Oh, I was not fully ready :) - i'll create another MR with more details to discuss.

**Comment by nesquena** [comment]
> Oh, I was not fully ready :) - i'll create another MR with more details to discuss.

Ah sorry for merging too early

**Comment by wikimatze** [comment]
No big things, I found several fixes to make Padrino ready for Ruby 3.0 - but those are other MRs.

**Comment by nesquena** [comment]
> No big things, I found several fixes to make Padrino ready for Ruby 3.0 - but those are other MRs.

Great thanks!

**Pull request merged**
